# TrustChain LTO - Complete Hyperledger Fabric Network
# All open source components extracted and configured
# This file contains ONLY the Fabric blockchain components

services:
  # ===========================================
  # CERTIFICATE AUTHORITY (CA)
  # ===========================================
  ca.lto.gov.ph:
    image: hyperledger/fabric-ca:1.5
    container_name: ca.lto.gov.ph
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.lto.gov.ph
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    ports:
      - "7054:7054"
      - "9443:9443"
    volumes:
      - ./fabric-network/crypto-config/peerOrganizations/lto.gov.ph/ca:/etc/hyperledger/fabric-ca-server-config
      - ca.lto.gov.ph:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - lto-network

  # ===========================================
  # ORDERER NODES (Raft Consensus)
  # ===========================================
  orderer1.lto.gov.ph:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer1.lto.gov.ph
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer1.lto.gov.ph/msp:/var/hyperledger/orderer/msp
      - ./fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer1.lto.gov.ph/tls/:/var/hyperledger/orderer/tls
      - ./fabric-network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - orderer1.lto.gov.ph:/var/hyperledger/production/orderer
    ports:
      - "7050:7050"
    depends_on:
      - ca.lto.gov.ph
    networks:
      - lto-network

  orderer2.lto.gov.ph:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer2.lto.gov.ph
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer2.lto.gov.ph/msp:/var/hyperledger/orderer/msp
      - ./fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer2.lto.gov.ph/tls/:/var/hyperledger/orderer/tls
      - ./fabric-network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - orderer2.lto.gov.ph:/var/hyperledger/production/orderer
    ports:
      - "8050:7050"
    depends_on:
      - ca.lto.gov.ph
    networks:
      - lto-network

  orderer3.lto.gov.ph:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer3.lto.gov.ph
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer3.lto.gov.ph/msp:/var/hyperledger/orderer/msp
      - ./fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer3.lto.gov.ph/tls/:/var/hyperledger/orderer/tls
      - ./fabric-network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - orderer3.lto.gov.ph:/var/hyperledger/production/orderer
    ports:
      - "9050:7050"
    depends_on:
      - ca.lto.gov.ph
    networks:
      - lto-network

  # ===========================================
  # PEER NODES
  # ===========================================
  peer0.lto.gov.ph:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.lto.gov.ph
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=lto-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.lto.gov.ph
      - CORE_PEER_ADDRESS=peer0.lto.gov.ph:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.lto.gov.ph:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lto.gov.ph:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lto.gov.ph:7051
      - CORE_PEER_LOCALMSPID=LTOMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-network/crypto-config/peerOrganizations/lto.gov.ph/peers/peer0.lto.gov.ph/msp:/etc/hyperledger/fabric/msp
      - ./fabric-network/crypto-config/peerOrganizations/lto.gov.ph/peers/peer0.lto.gov.ph/tls:/etc/hyperledger/fabric/tls
      - peer0.lto.gov.ph:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "7051:7051"
    depends_on:
      - couchdb0
      - ca.lto.gov.ph
      - orderer1.lto.gov.ph
      - orderer2.lto.gov.ph
      - orderer3.lto.gov.ph
    networks:
      - lto-network

  peer0.insurance.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.insurance.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=lto-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.insurance.com
      - CORE_PEER_ADDRESS=peer0.insurance.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.insurance.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.com:9051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-insurance:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-network/crypto-config/peerOrganizations/insurance.com/peers/peer0.insurance.com/msp:/etc/hyperledger/fabric/msp
      - ./fabric-network/crypto-config/peerOrganizations/insurance.com/peers/peer0.insurance.com/tls:/etc/hyperledger/fabric/tls
      - peer0.insurance.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "9051:9051"
    depends_on:
      - couchdb-insurance
      - ca.lto.gov.ph
      - orderer1.lto.gov.ph
      - orderer2.lto.gov.ph
      - orderer3.lto.gov.ph
    networks:
      - lto-network

  peer0.emission.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.emission.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=lto-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.emission.com
      - CORE_PEER_ADDRESS=peer0.emission.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.emission.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.emission.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.emission.com:10051
      - CORE_PEER_LOCALMSPID=EmissionMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-emission:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-network/crypto-config/peerOrganizations/emission.com/peers/peer0.emission.com/msp:/etc/hyperledger/fabric/msp
      - ./fabric-network/crypto-config/peerOrganizations/emission.com/peers/peer0.emission.com/tls:/etc/hyperledger/fabric/tls
      - peer0.emission.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "10051:10051"
    depends_on:
      - couchdb-emission
      - ca.lto.gov.ph
      - orderer1.lto.gov.ph
      - orderer2.lto.gov.ph
      - orderer3.lto.gov.ph
    networks:
      - lto-network

  peer0.hpg.gov.ph:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.hpg.gov.ph
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=lto-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.hpg.gov.ph
      - CORE_PEER_ADDRESS=peer0.hpg.gov.ph:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hpg.gov.ph:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hpg.gov.ph:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hpg.gov.ph:11051
      - CORE_PEER_LOCALMSPID=HPGMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-hpg:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-network/crypto-config/peerOrganizations/hpg.gov.ph/peers/peer0.hpg.gov.ph/msp:/etc/hyperledger/fabric/msp
      - ./fabric-network/crypto-config/peerOrganizations/hpg.gov.ph/peers/peer0.hpg.gov.ph/tls:/etc/hyperledger/fabric/tls
      - peer0.hpg.gov.ph:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "11051:11051"
    depends_on:
      - couchdb-hpg
      - ca.lto.gov.ph
      - orderer1.lto.gov.ph
      - orderer2.lto.gov.ph
      - orderer3.lto.gov.ph
    networks:
      - lto-network

  # ===========================================
  # COUCHDB (State Database)
  # ===========================================
  couchdb0:
    image: couchdb:3.2
    container_name: couchdb0
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    volumes:
      - couchdb0:/opt/couchdb/data
    networks:
      - lto-network

  couchdb-insurance:
    image: couchdb:3.2
    container_name: couchdb-insurance
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    volumes:
      - couchdb-insurance:/opt/couchdb/data
    networks:
      - lto-network

  couchdb-emission:
    image: couchdb:3.2
    container_name: couchdb-emission
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8984:5984"
    volumes:
      - couchdb-emission:/opt/couchdb/data
    networks:
      - lto-network

  couchdb-hpg:
    image: couchdb:3.2
    container_name: couchdb-hpg
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984"
    volumes:
      - couchdb-hpg:/opt/couchdb/data
    networks:
      - lto-network

  # ===========================================
  # FABRIC TOOLS (CLI)
  # ===========================================
  cli:
    image: hyperledger/fabric-tools:2.5
    container_name: cli
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ADDRESS=peer0.lto.gov.ph:7051
      - CORE_PEER_LOCALMSPID=LTOMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/lto.gov.ph/peers/peer0.lto.gov.ph/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/lto.gov.ph/users/Admin@lto.gov.ph/msp
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/lto.gov.ph/orderers/orderer1.lto.gov.ph/msp/tlscacerts/tlsca.lto.gov.ph-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-network/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./fabric-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./chaincode:/opt/gopath/src/github.com/chaincode
    depends_on:
      - peer0.lto.gov.ph
      - peer0.insurance.com
      - peer0.emission.com
      - peer0.hpg.gov.ph
      - orderer1.lto.gov.ph
      - orderer2.lto.gov.ph
      - orderer3.lto.gov.ph
    networks:
      - lto-network

volumes:
  ca.lto.gov.ph:
  orderer1.lto.gov.ph:
  orderer2.lto.gov.ph:
  orderer3.lto.gov.ph:
  peer0.lto.gov.ph:
  peer0.insurance.com:
  peer0.emission.com:
  peer0.hpg.gov.ph:
  couchdb0:
  couchdb-insurance:
  couchdb-emission:
  couchdb-hpg:

networks:
  lto-network:
    name: lto-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

