# TrustChain LTO - Crypto Configuration
# 3 Organizations: LTO, HPG, Insurance
# Single orderer with multi-org peer network

OrdererOrgs:
  - Name: Orderer
    Domain: lto.gov.ph
    Specs:
      - Hostname: orderer
        SANS:
          - "orderer.lto.gov.ph"
          - "localhost"
          - "127.0.0.1"
          - "::1"

PeerOrgs:
  - Name: LTO
    Domain: lto.gov.ph
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - "peer0.lto.gov.ph"
          - "localhost"
          - "127.0.0.1"
          - "::1"

  - Name: HPG
    Domain: hpg.gov.ph
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - "peer0.hpg.gov.ph"
          - "localhost"
          - "127.0.0.1"
          - "::1"

  - Name: Insurance
    Domain: insurance.gov.ph
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - "peer0.insurance.gov.ph"
          - "localhost"
          - "127.0.0.1"
          - "::1"

