# TrustChain LTO - Crypto Configuration
# Single orderer + LTO organization

OrdererOrgs:
  - Name: Orderer
    Domain: lto.gov.ph
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: LTO
    Domain: lto.gov.ph
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0

