# TrustChain LTO - Crypto Configuration
# Single orderer + LTO organization

OrdererOrgs:
  - Name: Orderer
    Domain: lto.gov.ph
    Specs:
      - Hostname: orderer
        SANS:
          - "orderer.lto.gov.ph"
          - "localhost"
          - "127.0.0.1"
          - "::1"

PeerOrgs:
  - Name: LTO
    Domain: lto.gov.ph
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - "peer0.lto.gov.ph"
          - "localhost"
          - "127.0.0.1"
          - "::1"

